spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/log
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
